env:
  browser: true
  es6: true
extends:
  - "plugin:react-app/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: ./
root: true
plugins:
  - "@typescript-eslint"
  - react
rules:
  react/jsx-no-duplicate-props: [1, { ignoreCase: false }]

